version: "3.9"
services:

  db:
    image: postgres:13.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: renatanerenata/devops-for-programmers-project-lvl1
    ports:
      - "8080:8080"
    volumes:
      - "/app"
    command: npm test


